export FZF_DEFAULT_OPTS="$FZF_DEFAULT_OPTS \
  --highlight-line \
  --info=inline-right \
  --ansi \
  --layout=reverse \
  --border=none \
  --color=bg+:#fdf5e2 \
  --color=bg:#ffffff \
  --color=border:#ede7d3 \
  --color=fg:#637981 \
  --color=gutter:#ffffff \
  --color=header:#c94c16 \
  --color=hl+:#c94c16 \
  --color=hl:#c94c16 \
  --color=info:#9eabac \
  --color=marker:#c94c16 \
  --color=pointer:#c94c16 \
  --color=prompt:#c94c16 \
  --color=query:#637981:regular \
  --color=scrollbar:#ede7d3 \
  --color=separator:#ede7d3 \
  --color=spinner:#c94c16 \
"
