# vim: ft=dosini
#
# aerc solarized-osaka styleset
# set styleset-name=solarized-osaka-xxx.ini in 'aerc.conf' to load the style
#

*.default=true
*.normal=true

border.fg=#adb7b7
border.bg=#fdf5e2

title.fg=#cac4b5
title.bg=#268bd3
title.bold=true

header.fg=#db302d
#header.bg=#fdf5e2
header.bold=true

tab.fg=#adb7b7
tab.bg=#fdf5e2
tab.selected.fg=#cac4b5
tab.selected.bg=#268bd3

statusline_default.fg=#576d74
statusline_default.bg=#fdf5e2
statusline_error.fg=#db302d
statusline_success.fg=#849900

*error.bold=true
*error.fg=#db302d
*warning.fg=#b28500
*success.fg=#849900

dirlist_*.bg=#fdf5e2
dirlist_*.fg=#576d74
dirlist_*.selected.bg=#46acf5
dirlist_*.selected.fg=#576d74

msglist_*.bg=#fdf5e2
msglist_*.fg=#576d74
msglist_*.selected.bg=#46acf5
#msglist_*.selected.fg=#576d74
msglist_unread.bold=true
msglist_unread.fg=#268bd3
msglist_marked.fg=#c94c16
msglist_thread_folded.italic=true
msglist_thread_folded.underline=true
msglist_gutter.bg=#ede7d3
msglist_pill.bg=#adb7b7
msglist_pill.reverse=false

part_*.fg=#576d74
part_*.bg=#ffffff
part_*.selected.fg=#576d74
part_*.selected.bg=#adb7b7

completion_default.bg=#ffffff
completion_default.fg=#576d74
completion_default.selected.bg=#adb7b7
completion_default.selected.fg=#576d74
completion_gutter.bg=#ede7d3
completion_pill.bg=#adb7b7
completion_pill.reverse=false

spinner.bg=#fdf5e2
spinner.fg=#576d74

selector_focused.bold=false
selector_focused.bg=#46acf5
selector_focused.fg=#576d74
selector_chooser.bold=false
selector_chooser.bg=#46acf5
selector_chooser.fg=#576d74
default.selected.bold=false
default.selected.fg=#576d74
default.selected.bg=#46acf5

[viewer]
url.underline=true
url.fg=#ede7d3
header.fg=#6d71c4
signature.fg=#d23681
diff_add.fg=#849900
diff_del.fg=#db302d
diff_meta.bold=true
diff_chunk.dim=true
quote_1.fg=#b28500
quote_2.fg=#849900
quote_3.fg=#29a298
quote_3.dim=true
quote_4.fg=#268bd3
quote_4.dim=true
quote_x.fg=#adb7b7
quote_x.dim=true

