[colors]
foreground = "#576d74"
background = "#fdf5e2"
cursor_bg = "#576d74"
cursor_border = "#576d74"
cursor_fg = "#fdf5e2"
selection_bg = "#46acf5"
selection_fg = "#576d74"

ansi = ["#cac4b5", "#db302d", "#849900", "#b28500", "#268bd3", "#d23681", "#29a298", "#637981"]
brights = ["#fdf5e2", "#db302d", "#849900", "#b28500", "#268bd3", "#d23681", "#29a298", "#576d74"]

[colors.tab_bar]
inactive_tab_edge = "#fdf5e2"
background = "#191b28"

[colors.tab_bar.active_tab]
fg_color = "#268bd3"
bg_color = "#fdf5e2"

[colors.tab_bar.inactive_tab]
bg_color = "#fdf5e2"
fg_color = "#ede7d3"

[colors.tab_bar.inactive_tab_hover]
bg_color = "#fdf5e2"
fg_color = "#268bd3"

[colors.tab_bar.new_tab_hover]
fg_color = "#fdf5e2"
bg_color = "#268bd3"

[colors.tab_bar.new_tab]
fg_color = "#268bd3"
bg_color = "#191b28"

[metadata]
aliases = []
author = "craftzdog"
name = "Solarized Osaka Light"