# solarized-osaka Alacritty Colors
colors:
  # Default colors
  primary:
    background: '0xfdf5e2'
    foreground: '0x576d74'

  # Normal colors
  normal:
    black:   '0xcac4b5'
    red:     '0xdb302d'
    green:   '0x849900'
    yellow:  '0xb28500'
    blue:    '0x268bd3'
    magenta: '0xd23681'
    cyan:    '0x29a298'
    white:   '0x637981'

  # Bright colors
  bright:
    black:   '0xfdf5e2'
    red:     '0xdb302d'
    green:   '0x849900'
    yellow:  '0xb28500'
    blue:    '0x268bd3'
    magenta: '0xd23681'
    cyan:    '0x29a298'
    white:   '0x576d74'

  indexed_colors:
    - { index: 16, color: '0xc94c16' }
    - { index: 17, color: '0xb7211f' }
    
  