[[themes]]
name = "Solarized Osaka Light"
[themes.palette]
background = "#fdf5e2"
foreground = "#637981"
black = "#fdf5e2"
red = "#db302d"
green = "#849900"
yellow = "#b28500"
blue = "#268bd3"
magenta = "#d23681"
cyan = "#29a298"
white = "#ffffff"
bright_black = "#fdf5e2"
bright_red = "#b7211f"
bright_green = "#849900"
bright_yellow = "#c94c16"
bright_blue = "#1a6397"
bright_magenta = "#af2668"
bright_cyan = "#46acf5"
bright_white = "#576d74"
