# -----------------------------------------------------------------------------
# Theme: Solarized Osaka Light
# Upstream: https://github.com/craftzdog/solarized-osaka.nvim/raw/main/extras/termux/solarized_osaka_light.properties
# -----------------------------------------------------------------------------

background: #fdf5e2
foreground: #576d74

# Normal colors
color0:  #ffffff
color1:  #db302d
color2:  #849900
color3:  #b28500
color4:  #268bd3
color5:  #d23681
color6:  #29a298
color7:  #002c38

# Bright colors
color8:  #ede7d3
color9:  #b7211f
color10: #586600
color11: #664c00
color12: #1a6397
color13: #af2668
color14: #1a6265
color15: #001419

# Extended colors
color16: #c94c16
color17: #f55350
